set(CMAKE_C_COMPILER gcc CACHE FILEPATH "C Compiler")
set(CMAKE_CXX_COMPILER g++ CACHE FILEPATH "C++ Compiler")

set(CMAKE_FIND_ROOT_PATH 
    /usr/include/x86_64-linux-gnu/qt5/
    /usr/lib/x86_64-linux-gnu/
)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)